"""Whole-suite orchestration and provenance rendering."""

from __future__ import annotations

import ast
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

from transpilation_helper import py_identifier_to_ts

from .assertion_oracle import (
    GENERATED_ASSERTION_ORACLE,
    compile_assertion_oracle,
)
from .gaps import PARITY_GAPS, ast_fingerprint, validate_manifest
from .lower import compile_method
from .model import SourceUnit
from .selection import TRANSLATED_TESTS
from .source import load_source_unit, parse_source_unit


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
UPSTREAM_TEST = REPOSITORY_ROOT / "python-chess" / "test.py"
GENERATED_TEST = REPOSITORY_ROOT / "chess" / "test" / "python-generated.test.ts"
GENERATED_PROVENANCE = (
    REPOSITORY_ROOT / "chess" / "test" / "python-generated.provenance.json"
)
UPSTREAM_COMMIT = "8330cfd5dbb9401f0e85be92cf408d6482505642"


@dataclass(frozen=True, slots=True)
class CompiledSuite:
    typescript: str
    provenance: str


def _source_sha256(source: str) -> str:
    return hashlib.sha256(source.encode("utf-8")).hexdigest()


def _is_upstream_assertion(node: ast.AST) -> bool:
    return (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and isinstance(node.func.value, ast.Name)
        and node.func.value.id == "self"
        and node.func.attr.startswith("assert")
    )


def _semantic_node_count(node: ast.AST) -> int:
    return sum(
        isinstance(child, (ast.stmt, ast.expr, ast.comprehension))
        for child in ast.walk(node)
    )


def compile_suite(source: str | None = None) -> CompiledSuite:
    """Compile all 89 methods from one parsed frozen source unit."""

    if source is None:
        source_unit = load_source_unit(UPSTREAM_TEST, TRANSLATED_TESTS)
    else:
        source_unit = parse_source_unit(
            source, TRANSLATED_TESTS, filename=str(UPSTREAM_TEST)
        )
    validate_manifest(PARITY_GAPS, source_unit)

    lines = [
        "// Generated by scripts/sync_python_chess_tests.py; do not edit by hand.",
        f"// Source: python-chess test.py at {UPSTREAM_COMMIT}.",
        "// Every selected method body and source comment is lowered from Python's AST/tokens.",
        "import * as chess from '../index'",
        "import * as engineModule from '../engine'",
        "import * as pgnModule from '../pgn'",
        "import * as svgModule from '../svg'",
        "import { openTextFixture, registerTestCase, TestCase } from './unittest'",
        "",
    ]
    provenance_methods: list[dict[str, object]] = []

    current_class: str | None = None
    class_methods: list[tuple[str, int]] = []

    def close_class() -> None:
        if current_class is None:
            return
        lines.extend(
            [
                "}",
                "",
                f"registerTestCase('{current_class}', {current_class}, {{",
                "  lines: {",
            ]
        )
        for method_name, line in class_methods:
            lines.append(f"    {method_name}: {line},")
        lines.extend(["  },", "})", ""])

    for method in source_unit.methods:
        identity = method.identity
        if identity.class_name != current_class:
            close_class()
            current_class = identity.class_name
            class_methods = []
            lines.extend(
                [
                    "/** Generated directly from the frozen python-chess syntax tree. */",
                    f"class {current_class} extends TestCase {{",
                ]
            )
        elif class_methods:
            lines.append("")

        lines.extend(compile_method(source_unit, method))
        method_name = py_identifier_to_ts(identity.method_name)
        class_methods.append((method_name, method.node.lineno))
        exact_source = source_unit.source_for(method.span)
        assertion_count = sum(
            _is_upstream_assertion(node) for node in ast.walk(method.node)
        )
        provenance_methods.append(
            {
                "identity": str(identity),
                "sourceSpan": {
                    "start": list(method.span.start_position),
                    "end": list(method.span.end_position),
                },
                "sourceSha256": _source_sha256(exact_source),
                "astSha256": ast_fingerprint(method.node),
                "semanticNodeCount": _semantic_node_count(method.node),
                "assertionCount": assertion_count,
                "comments": [
                    {
                        "span": {
                            "start": list(comment.span.start_position),
                            "end": list(comment.span.end_position),
                        },
                        "placement": comment.placement.value,
                        "text": comment.text,
                    }
                    for comment in method.comments
                ],
                "parityGapCases": [
                    case.stable_id for case in PARITY_GAPS.cases_for(identity)
                ],
            }
        )

    close_class()
    provenance = {
        "schemaVersion": 1,
        "upstreamCommit": UPSTREAM_COMMIT,
        "sourcePath": "python-chess/test.py",
        "translatedMethodCount": len(source_unit.methods),
        "sourceCommentCount": len(source_unit.comments),
        "semanticNodeCount": sum(
            _semantic_node_count(method.node) for method in source_unit.methods
        ),
        "assertionCount": sum(
            method["assertionCount"] for method in provenance_methods
        ),
        "parityGapRootCount": len(PARITY_GAPS.roots),
        "parityGapCaseCount": len(PARITY_GAPS.cases),
        "methods": provenance_methods,
    }
    return CompiledSuite(
        typescript="\n".join(lines),
        provenance=json.dumps(provenance, indent=2, ensure_ascii=False) + "\n",
    )


def sync_compiled_suite(*, check: bool) -> int:
    compiled = compile_suite()
    assertion_oracle = compile_assertion_oracle()
    expected = {
        GENERATED_TEST: compiled.typescript,
        GENERATED_PROVENANCE: compiled.provenance,
        GENERATED_ASSERTION_ORACLE: assertion_oracle.typescript,
    }
    if check:
        stale = [
            path
            for path, contents in expected.items()
            if not path.exists() or path.read_text(encoding="utf-8") != contents
        ]
        if stale:
            relative = ", ".join(
                str(path.relative_to(REPOSITORY_ROOT)) for path in stale
            )
            raise SystemExit(
                "Generated upstream test artifacts are stale: "
                f"{relative}. Run `python3 scripts/sync_python_chess_tests.py`."
            )
    else:
        for path, contents in expected.items():
            path.write_text(contents, encoding="utf-8", newline="\n")
    return len(TRANSLATED_TESTS)
