// Generated by scripts/sync_python_chess_tests.py; do not edit by hand.
// Source: python-chess test.py at caefd4dc6c25369750f6cc461885adfbbd52f09c.
// Every selected method body and source comment is lowered from Python's AST/tokens.
import * as chess from '../index'
import * as engineModule from '../engine'
import * as pgnModule from '../pgn'
import * as svgModule from '../svg'
import { registerTestCase, TestCase } from './unittest'

/** Generated directly from the frozen python-chess syntax tree. */
class SquareTestCase extends TestCase {
  testSquare(): void {
    for (let square of chess.SQUARES) {
      const fileIndex = chess.squareFile(square)
      const rankIndex = chess.squareRank(square)
      this.assertEqualUsing(chess.square(fileIndex, rankIndex), square, (__actual, __expected) => __actual === __expected, chess.squareName(square))
    }
  }

  testShifts(): void {
    const shifts = [chess.shiftDown, chess.shift2Down, chess.shiftUp, chess.shift2Up, chess.shiftRight, chess.shift2Right, chess.shiftLeft, chess.shift2Left, chess.shiftUpLeft, chess.shiftUpRight, chess.shiftDownLeft, chess.shiftDownRight]

    for (let shift of shifts) {
      for (let bbSquare of chess.BB_SQUARES) {
        const shifted = shift(bbSquare)
        const c = chess.popcount(shifted)
        this.assertLessEqual(c, 1)
        this.assertEqualUsing(c, chess.popcount((shifted & chess.BB_ALL)), (__actual, __expected) => __actual === __expected)
      }
    }
  }

  testParseSquare(): void {
    this.assertEqualUsing(chess.parseSquare("a1"), 0, (__actual, __expected) => __actual === __expected)
    this.assertRaises(chess.ValueError, () => {
      this.assertEqual(chess.parseSquare("A1"))
    })
    this.assertRaises(chess.ValueError, () => {
      this.assertEqual(chess.parseSquare("a0"))
    })
  }

  testSquareDistance(): void {
    this.assertEqualUsing(chess.squareDistance(chess.A1, chess.A1), 0, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareDistance(chess.A1, chess.H8), 7, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareDistance(chess.E1, chess.E8), 7, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareDistance(chess.A4, chess.H4), 7, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareDistance(chess.D4, chess.E5), 1, (__actual, __expected) => __actual === __expected)
  }

  testSquareManhattanDistance(): void {
    this.assertEqualUsing(chess.squareManhattanDistance(chess.A1, chess.A1), 0, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareManhattanDistance(chess.A1, chess.H8), 14, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareManhattanDistance(chess.E1, chess.E8), 7, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareManhattanDistance(chess.A4, chess.H4), 7, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareManhattanDistance(chess.D4, chess.E5), 2, (__actual, __expected) => __actual === __expected)
  }

  testSquareKnightDistance(): void {
    this.assertEqualUsing(chess.squareKnightDistance(chess.A1, chess.A1), 0, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareKnightDistance(chess.A1, chess.H8), 6, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareKnightDistance(chess.G1, chess.F3), 1, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareKnightDistance(chess.E1, chess.E8), 5, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareKnightDistance(chess.A4, chess.H4), 5, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareKnightDistance(chess.A1, chess.B1), 3, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareKnightDistance(chess.A1, chess.C3), 4, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareKnightDistance(chess.A1, chess.B2), 4, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.squareKnightDistance(chess.C1, chess.B2), 2, (__actual, __expected) => __actual === __expected)
  }
}

registerTestCase('SquareTestCase', SquareTestCase, {
  lines: {
    testSquare: 44,
    testShifts: 50,
    testParseSquare: 73,
    testSquareDistance: 80,
    testSquareManhattanDistance: 87,
    testSquareKnightDistance: 94,
  },
})

/** Generated directly from the frozen python-chess syntax tree. */
class MoveTestCase extends TestCase {
  testEquality(): void {
    const a = new chess.Move(chess.A1, chess.A2)
    const b = new chess.Move(chess.A1, chess.A2)
    const c = new chess.Move(chess.H7, chess.H8, { promotion: chess.BISHOP })
    const d1 = new chess.Move(chess.H7, chess.H8)
    const d2 = new chess.Move(chess.H7, chess.H8)

    this.assertEqualUsing(a, b, (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(b, a, (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(d1, d2, (__actual, __expected) => __actual.equals(__expected))

    this.assertNotEqualUsing(a, c, (__actual, __expected) => __actual.equals(__expected))
    this.assertNotEqualUsing(c, d1, (__actual, __expected) => __actual.equals(__expected))
    this.assertNotEqualUsing(b, d1, (__actual, __expected) => __actual.equals(__expected))
    this.assertFalse(!(((__left, __right) => __left.equals(__right))(d1, d2)))
  }

  testUciParsing(): void {
    this.assertEqualUsing(chess.Move.fromUci("b5c7").uci(), "b5c7", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.Move.fromUci("e7e8q").uci(), "e7e8q", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.Move.fromUci("P@e4").uci(), "P@e4", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.Move.fromUci("B@f4").uci(), "B@f4", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.Move.fromUci("0000").uci(), "0000", (__actual, __expected) => __actual === __expected)
  }

  testInvalidUci(): void {
    this.assertRaises(chess.InvalidMoveError, () => {
      chess.Move.fromUci("")
    })

    this.assertRaises(chess.InvalidMoveError, () => {
      chess.Move.fromUci("N")
    })

    this.assertRaises(chess.InvalidMoveError, () => {
      chess.Move.fromUci("z1g3")
    })

    this.assertRaises(chess.InvalidMoveError, () => {
      chess.Move.fromUci("Q@g9")
    })
  }

  testXboardMove(): void {
    this.assertEqualUsing(chess.Move.fromUci("b5c7").xboard(), "b5c7", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.Move.fromUci("e7e8q").xboard(), "e7e8q", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.Move.fromUci("P@e4").xboard(), "P@e4", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.Move.fromUci("B@f4").xboard(), "B@f4", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.Move.fromUci("0000").xboard(), "@@@@", (__actual, __expected) => __actual === __expected)
  }

  testCopy(): void {
    const a = chess.Move.fromUci("N@f3")
    const b = chess.Move.fromUci("a1h8")
    const c = chess.Move.fromUci("g7g8r")
    this.assertEqualUsing(a.copy(), a, (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(b.copy(), b, (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(c.copy(), c, (__actual, __expected) => __actual.equals(__expected))
  }
}

registerTestCase('MoveTestCase', MoveTestCase, {
  lines: {
    testEquality: 108,
    testUciParsing: 124,
    testInvalidUci: 131,
    testXboardMove: 144,
    testCopy: 151,
  },
})

/** Generated directly from the frozen python-chess syntax tree. */
class PieceTestCase extends TestCase {
  testEquality(): void {
    const a = new chess.Piece(chess.BISHOP, chess.WHITE)
    const b = new chess.Piece(chess.KING, chess.BLACK)
    const c = new chess.Piece(chess.KING, chess.WHITE)
    const d1 = new chess.Piece(chess.BISHOP, chess.WHITE)
    const d2 = new chess.Piece(chess.BISHOP, chess.WHITE)

    this.assertEqualUsing((Array.from([a, b, c, d1, d2])).filter((__value, __index, __values) => !__values.slice(0, __index).some(__candidate => (() => { const __piece = __candidate; const __other = __value; if (__piece.hash() !== __other.hash()) return false; return __piece.equals(__other); })())).length, 3, (__actual, __expected) => __actual === __expected)

    this.assertEqualUsing(a, d1, (__actual, __expected) => (__actual).equals(__expected))
    this.assertEqualUsing(d1, a, (__actual, __expected) => (__actual).equals(__expected))
    this.assertEqualUsing(d1, d2, (__actual, __expected) => (__actual).equals(__expected))

    ;((__actualRepresentation, __expectedRepresentation) => this.assertEqualRepresentationsUsing(__actualRepresentation.representation, __expectedRepresentation.representation, (__actual, __expected) => __actual === __expected, __actualRepresentation.value, __expectedRepresentation.value))(((__representedValue) => ({ representation: __representedValue.toRepr(), value: __representedValue }))(a), ((__representedValue) => ({ representation: __representedValue.toRepr(), value: __representedValue }))(d1))

    this.assertNotEqualUsing(a, b, (__actual, __expected) => (__actual).equals(__expected))
    this.assertNotEqualUsing(b, c, (__actual, __expected) => (__actual).equals(__expected))
    this.assertNotEqualUsing(b, d1, (__actual, __expected) => (__actual).equals(__expected))
    this.assertNotEqualUsing(a, c, (__actual, __expected) => (__actual).equals(__expected))
    this.assertFalse(!(((__left, __right) => (__left).equals(__right))(d1, d2)))

    ;((__actualRepresentation, __expectedRepresentation) => this.assertNotEqualRepresentationsUsing(__actualRepresentation.representation, __expectedRepresentation.representation, (__actual, __expected) => __actual === __expected, __actualRepresentation.value, __expectedRepresentation.value))(((__representedValue) => ({ representation: __representedValue.toRepr(), value: __representedValue }))(a), ((__representedValue) => ({ representation: __representedValue.toRepr(), value: __representedValue }))(b))
    ;((__actualRepresentation, __expectedRepresentation) => this.assertNotEqualRepresentationsUsing(__actualRepresentation.representation, __expectedRepresentation.representation, (__actual, __expected) => __actual === __expected, __actualRepresentation.value, __expectedRepresentation.value))(((__representedValue) => ({ representation: __representedValue.toRepr(), value: __representedValue }))(b), ((__representedValue) => ({ representation: __representedValue.toRepr(), value: __representedValue }))(c))
    ;((__actualRepresentation, __expectedRepresentation) => this.assertNotEqualRepresentationsUsing(__actualRepresentation.representation, __expectedRepresentation.representation, (__actual, __expected) => __actual === __expected, __actualRepresentation.value, __expectedRepresentation.value))(((__representedValue) => ({ representation: __representedValue.toRepr(), value: __representedValue }))(b), ((__representedValue) => ({ representation: __representedValue.toRepr(), value: __representedValue }))(d1))
    ;((__actualRepresentation, __expectedRepresentation) => this.assertNotEqualRepresentationsUsing(__actualRepresentation.representation, __expectedRepresentation.representation, (__actual, __expected) => __actual === __expected, __actualRepresentation.value, __expectedRepresentation.value))(((__representedValue) => ({ representation: __representedValue.toRepr(), value: __representedValue }))(a), ((__representedValue) => ({ representation: __representedValue.toRepr(), value: __representedValue }))(c))
  }

  testFromSymbol(): void {
    const whiteKnight = chess.Piece.fromSymbol("N")

    this.assertEqualUsing(whiteKnight.color, chess.WHITE, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(whiteKnight.pieceType, chess.KNIGHT, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(whiteKnight.symbol(), "N", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(whiteKnight.symbol(), "N", (__actual, __expected) => __actual === __expected)

    const blackQueen = chess.Piece.fromSymbol("q")

    this.assertEqualUsing(blackQueen.color, chess.BLACK, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(blackQueen.pieceType, chess.QUEEN, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(blackQueen.symbol(), "q", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(blackQueen.symbol(), "q", (__actual, __expected) => __actual === __expected)
  }

  testHash(): void {
    const pieces = (Array.from("pnbrqkPNBRQK", __symbolItem => chess.Piece.fromSymbol(__symbolItem))).filter((__value, __index, __values) => !__values.slice(0, __index).some(__candidate => (() => { const __piece = __candidate; const __other = __value; if (__piece.hash() !== __other.hash()) return false; return __piece.equals(__other); })()))
    this.assertEqualUsing(pieces.length, 12, (__actual, __expected) => __actual === __expected)
    const hashes = new Set(Array.from(pieces, __pieceItem => __pieceItem.hash()))
    this.assertEqualUsing(hashes, new Set(Array.from(({ *[Symbol.iterator]() { for (let __index = 0; __index < 12; __index += 1) { yield __index; } } }))), (__actual, __expected) => __actual.size === __expected.size && Array.from(__actual).every(__setValue => __expected.has(__setValue)))
  }
}

registerTestCase('PieceTestCase', PieceTestCase, {
  lines: {
    testEquality: 162,
    testFromSymbol: 188,
    testHash: 203,
  },
})

/** Generated directly from the frozen python-chess syntax tree. */
class BoardTestCase extends TestCase {
  testDefaultPosition(): void {
    const board = new chess.Board()
    this.assertEqualUsing(board.pieceAt(chess.B1), chess.Piece.fromSymbol("N"), (__actual, __expected) => __actual !== null && ((__actual).equals(__expected)))
    this.assertEqualUsing(board.fen(), chess.STARTING_FEN, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.turn, chess.WHITE, (__actual, __expected) => __actual === __expected)
  }

  testEmpty(): void {
    const board = chess.Board.empty()
    this.assertEqualUsing(board.fen(), "8/8/8/8/8/8/8/8 w - - 0 1", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board, new chess.Board(null), (__actual, __expected) => __actual.equals(__expected))
  }

  testPly(): void {
    const board = new chess.Board()
    this.assertEqualUsing(board.ply(), 0, (__actual, __expected) => __actual === __expected)
    board.pushSan("d4")
    this.assertEqualUsing(board.ply(), 1, (__actual, __expected) => __actual === __expected)
    board.pushSan("d5")
    this.assertEqualUsing(board.ply(), 2, (__actual, __expected) => __actual === __expected)
    board.clearStack()
    this.assertEqualUsing(board.ply(), 2, (__actual, __expected) => __actual === __expected)
    board.pushSan("Nf3")
    this.assertEqualUsing(board.ply(), 3, (__actual, __expected) => __actual === __expected)
  }

  testFromEpd(): void {
    const baseEpd = "rnbqkb1r/ppp1pppp/5n2/3P4/8/8/PPPP1PPP/RNBQKBNR w KQkq -"
    const [board, ops] = chess.Board.fromEpd((baseEpd + " ce 55;"))
    this.assertEqualUsing(((__mapping, __key) => { const __mappedValue = __mapping.get(__key); if (__mappedValue === undefined) throw new chess.KeyError(String(__key)); return __mappedValue; })(ops, "ce"), 55, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), (baseEpd + " 0 1"), (__actual, __expected) => __actual === __expected)
  }

  testSetFenAsEpd(): void {
    const board = new chess.Board()
    this.assertRaises(chess.ValueError, () => {
      board.setEpd(board.fen()) // Move numbers are not valid opcodes
    })
  }

  testMoveMaking(): void {
    const board = new chess.Board()
    const move = new chess.Move(chess.E2, chess.E4)
    board.push(move)
    this.assertEqualUsing(board.peek(), move, (__actual, __expected) => __actual.equals(__expected))
  }

  testFen(): void {
    const board = new chess.Board()
    this.assertEqualUsing(board.fen(), chess.STARTING_FEN, (__actual, __expected) => __actual === __expected)

    const fen = "6k1/pb3pp1/1p2p2p/1Bn1P3/8/5N2/PP1q1PPP/6K1 w - - 0 24"
    board.setFen(fen)
    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)

    board.push(chess.Move.fromUci("f3d2"))
    this.assertEqualUsing(board.fen(), "6k1/pb3pp1/1p2p2p/1Bn1P3/8/8/PP1N1PPP/6K1 b - - 0 24", (__actual, __expected) => __actual === __expected)
  }

  testXfen(): void {
    // https://de.wikipedia.org/wiki/Forsyth-Edwards-Notation#Beispiel
    const xfen = "rn2k1r1/ppp1pp1p/3p2p1/5bn1/P7/2N2B2/1PPPPP2/2BNK1RR w Gkq - 4 11"
    let board = new chess.Board(xfen, { chess960: true })
    this.assertEqualUsing(board.castlingRights, ((chess.BB_G1 | chess.BB_A8) | chess.BB_G8), (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.cleanCastlingRights(), ((chess.BB_G1 | chess.BB_A8) | chess.BB_G8), (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.shredderFen(), "rn2k1r1/ppp1pp1p/3p2p1/5bn1/P7/2N2B2/1PPPPP2/2BNK1RR w Gga - 4 11", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), xfen, (__actual, __expected) => __actual === __expected)
    this.assertTrue(board.hasCastlingRights(chess.WHITE))
    this.assertTrue(board.hasCastlingRights(chess.BLACK))
    this.assertTrue(board.hasKingsideCastlingRights(chess.BLACK))
    this.assertTrue(board.hasKingsideCastlingRights(chess.WHITE))
    this.assertTrue(board.hasQueensideCastlingRights(chess.BLACK))
    this.assertFalse(board.hasQueensideCastlingRights(chess.WHITE))

    // Chess960 position #284.
    board = new chess.Board("rkbqrbnn/pppppppp/8/8/8/8/PPPPPPPP/RKBQRBNN w - - 0 1", { chess960: true })
    ;((__newValue, __receiver) => { __receiver.castlingRights = __newValue; })(board.rooks, board)
    this.assertTrue((board.cleanCastlingRights() & chess.BB_A1) !== 0n)
    this.assertEqualUsing(board.fen(), "rkbqrbnn/pppppppp/8/8/8/8/PPPPPPPP/RKBQRBNN w KQkq - 0 1", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.shredderFen(), "rkbqrbnn/pppppppp/8/8/8/8/PPPPPPPP/RKBQRBNN w EAea - 0 1", (__actual, __expected) => __actual === __expected)

    // Valid en passant square on illegal board.
    let fen = "8/8/8/pP6/8/8/8/8 w - a6 0 1"
    board = new chess.Board(fen)
    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)

    // Illegal en passant square on illegal board.
    fen = "1r6/8/8/pP6/8/8/8/1K6 w - a6 0 1"
    board = new chess.Board(fen)
    this.assertEqualUsing(board.fen(), "1r6/8/8/pP6/8/8/8/1K6 w - - 0 1", (__actual, __expected) => __actual === __expected)
  }

  testFenEnPassant(): void {
    const board = new chess.Board()
    board.pushSan("e4")
    this.assertEqualUsing(board.fen({ enPassant: "fen" }), "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen({ enPassant: "xfen" }), "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1", (__actual, __expected) => __actual === __expected)
  }

  testGetSet(): void {
    const board = new chess.Board()
    this.assertEqualUsing(board.pieceAt(chess.B1), chess.Piece.fromSymbol("N"), (__actual, __expected) => __actual !== null && ((__actual).equals(__expected)))

    board.removePieceAt(chess.E2)
    this.assertEqualUsing(board.pieceAt(chess.E2), null, (__actual, __expected) => __actual === null)

    board.setPieceAt(chess.E4, chess.Piece.fromSymbol("r"))
    this.assertEqualUsing(board.pieceTypeAt(chess.E4), chess.ROOK, (__actual, __expected) => __actual !== null && (__actual === __expected))

    board.setPieceAt(chess.F1, null)
    this.assertEqualUsing(board.pieceAt(chess.F1), null, (__actual, __expected) => __actual === null)

    board.setPieceAt(chess.H7, chess.Piece.fromSymbol("Q"), true)
    this.assertEqualUsing(board.promoted, chess.BB_H7, (__actual, __expected) => __actual === __expected)

    board.setPieceAt(chess.H7, null)
    this.assertEqualUsing(board.promoted, chess.BB_EMPTY, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.pieceAt(chess.H7), null, (__actual, __expected) => __actual === null)
  }

  testColorAt(): void {
    const board = new chess.Board()
    this.assertEqualUsing(board.colorAt(chess.A1), chess.WHITE, (__actual, __expected) => __actual !== null && (__actual === __expected))
    this.assertEqualUsing(board.colorAt(chess.G7), chess.BLACK, (__actual, __expected) => __actual !== null && (__actual === __expected))
    this.assertEqualUsing(board.colorAt(chess.E4), null, (__actual, __expected) => __actual === null)
  }

  testPawnCaptures(): void {
    const board = new chess.Board()

    // King's Gambit.
    board.push(chess.Move.fromUci("e2e4"))
    board.push(chess.Move.fromUci("e7e5"))
    board.push(chess.Move.fromUci("f2f4"))

    // Accepted.
    const exf4 = chess.Move.fromUci("e5f4")
    this.assertContainsUsing(exf4, board.pseudoLegalMoves, (__container, __member) => __container.contains(__member))
    this.assertContainsUsing(exf4, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(exf4)
    board.pop()
  }

  testPawnMoveGeneration(): void {
    const board = new chess.Board("8/2R1P3/8/2pp4/2k1r3/P7/8/1K6 w - - 1 55")
    this.assertEqualUsing(Array.from(board.generatePseudoLegalMoves()).length, 16, (__actual, __expected) => __actual === __expected)
  }

  testSingleStepPawnMove(): void {
    const board = new chess.Board()
    const a3 = chess.Move.fromUci("a2a3")
    this.assertContainsUsing(a3, board.pseudoLegalMoves, (__container, __member) => __container.contains(__member))
    this.assertContainsUsing(a3, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(a3)
    board.pop()
    this.assertEqualUsing(board.fen(), chess.STARTING_FEN, (__actual, __expected) => __actual === __expected)
  }

  testCastling(): void {
    const board = new chess.Board("r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 1 1")

    // Let white castle short.
    let move = board.parseXboard("O-O")
    this.assertEqualUsing(move, chess.Move.fromUci("e1g1"), (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(board.san(move), "O-O", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.xboard(move), "e1g1", (__actual, __expected) => __actual === __expected)
    this.assertContainsUsing(move, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(move)

    // Let black castle long.
    move = board.parseXboard("O-O-O")
    this.assertEqualUsing(board.san(move), "O-O-O", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.xboard(move), "e8c8", (__actual, __expected) => __actual === __expected)
    this.assertContainsUsing(move, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(move)
    this.assertEqualUsing(board.fen(), "2kr3r/8/8/8/8/8/8/R4RK1 w - - 3 2", (__actual, __expected) => __actual === __expected)

    // Undo both castling moves.
    board.pop()
    board.pop()
    this.assertEqualUsing(board.fen(), "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 1 1", (__actual, __expected) => __actual === __expected)

    // Let white castle long.
    move = board.parseSan("O-O-O")
    this.assertEqualUsing(board.san(move), "O-O-O", (__actual, __expected) => __actual === __expected)
    this.assertContainsUsing(move, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(move)

    // Let black castle short.
    move = board.parseSan("O-O")
    this.assertEqualUsing(board.san(move), "O-O", (__actual, __expected) => __actual === __expected)
    this.assertContainsUsing(move, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(move)
    this.assertEqualUsing(board.fen(), "r4rk1/8/8/8/8/8/8/2KR3R w - - 3 2", (__actual, __expected) => __actual === __expected)

    // Undo both castling moves.
    board.pop()
    board.pop()
    this.assertEqualUsing(board.fen(), "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 1 1", (__actual, __expected) => __actual === __expected)
  }

  testCastlingSan(): void {
    const board = new chess.Board("4k3/8/8/8/8/8/8/4K2R w K - 0 1")
    this.assertEqualUsing(board.parseSan("O-O"), chess.Move.fromUci("e1g1"), (__actual, __expected) => __actual.equals(__expected))
    this.assertRaises(chess.IllegalMoveError, () => {
      board.parseSan("Kg1")
    })
    this.assertRaises(chess.IllegalMoveError, () => {
      board.parseSan("Kh1")
    })
  }

  testNinesixtyCastling(): void {
    let fen = "3r1k1r/4pp2/8/8/8/8/8/4RKR1 w Gd - 1 1"
    let board = new chess.Board(fen, { chess960: true })

    // Let white do the kingside swap.
    let move = board.parseSan("O-O")
    this.assertEqualUsing(board.san(move), "O-O", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.xboard(move), "O-O", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(move.fromSquare, chess.F1, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(move.toSquare, chess.G1, (__actual, __expected) => __actual === __expected)
    this.assertContainsUsing(move, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(move)
    this.assertEqualUsing(board.shredderFen(), "3r1k1r/4pp2/8/8/8/8/8/4RRK1 b d - 2 1", (__actual, __expected) => __actual === __expected)

    // Black can not castle kingside.
    this.assertNotContainsUsing(chess.Move.fromUci("e8h8"), board.legalMoves, (__container, __member) => __container.contains(__member))

    // Let black castle queenside.
    move = board.parseSan("O-O-O")
    this.assertEqualUsing(board.san(move), "O-O-O", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.xboard(move), "O-O-O", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(move.fromSquare, chess.F8, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(move.toSquare, chess.D8, (__actual, __expected) => __actual === __expected)
    this.assertContainsUsing(move, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(move)
    this.assertEqualUsing(board.shredderFen(), "2kr3r/4pp2/8/8/8/8/8/4RRK1 w - - 3 2", (__actual, __expected) => __actual === __expected)

    // Restore initial position.
    board.pop()
    board.pop()
    this.assertEqualUsing(board.shredderFen(), fen, (__actual, __expected) => __actual === __expected)

    fen = "Qr4k1/4pppp/8/8/8/8/8/R5KR w Hb - 0 1"
    board = new chess.Board(fen, { chess960: true })

    // White can just hop the rook over.
    move = board.parseSan("O-O")
    this.assertEqualUsing(board.san(move), "O-O", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(move.fromSquare, chess.G1, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(move.toSquare, chess.H1, (__actual, __expected) => __actual === __expected)
    this.assertContainsUsing(move, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(move)
    this.assertEqualUsing(board.shredderFen(), "Qr4k1/4pppp/8/8/8/8/8/R4RK1 b b - 1 1", (__actual, __expected) => __actual === __expected)

    // Black can not castle queenside nor kingside.
    this.assertFalse((() => { for (const __item of board.generateCastlingMoves()) { if (__item.bool()) return true; } return false; })())

    // Restore initial position.
    board.pop()
    this.assertEqualUsing(board.shredderFen(), fen, (__actual, __expected) => __actual === __expected)
  }

  testHsideRookBlocksAsideCastling(): void {
    const board = new chess.Board("4rrk1/pbbp2p1/1ppnp3/3n1pqp/3N1PQP/1PPNP3/PBBP2P1/4RRK1 w Ff - 10 18", { chess960: true })
    this.assertNotContainsUsing(chess.Move.fromUci("g1f1"), board.legalMoves, (__container, __member) => __container.contains(__member))
    this.assertNotContainsUsing(chess.Move.fromUci("g1e1"), board.legalMoves, (__container, __member) => __container.contains(__member))
    this.assertNotContainsUsing(chess.Move.fromUci("g1c1"), board.legalMoves, (__container, __member) => __container.contains(__member))
    this.assertNotContainsUsing(chess.Move.fromUci("g1a1"), board.legalMoves, (__container, __member) => __container.contains(__member))
    this.assertContainsUsing(chess.Move.fromUci("g1h1"), board.legalMoves, (__container, __member) => __container.contains(__member)) // Kh1
  }

  testSelectiveCastling(): void {
    const board = new chess.Board("r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1")

    // King not selected.
    this.assertFalse((() => { for (const __item of board.generateCastlingMoves((chess.BB_ALL & ~(board.kings)))) { if (__item.bool()) return true; } return false; })())

    // Rook on h1 not selected.
    const moves = board.generateCastlingMoves(chess.BB_ALL, (chess.BB_ALL & ~(chess.BB_H1)))
    this.assertEqualUsing(Array.from(moves).length, 1, (__actual, __expected) => __actual === __expected)
  }

  testCastlingRightNotDestroyedBug(): void {
    // A rook move from h8 to h1 was only taking white's possible castling
    // rights away.
    const board = new chess.Board("2r1k2r/2qbbpp1/p2pp3/1p3PP1/Pn2P3/1PN1B3/1P3QB1/1K1R3R b k - 0 22")
    board.pushSan("Rxh1")
    this.assertEqualUsing(board.epd(), "2r1k3/2qbbpp1/p2pp3/1p3PP1/Pn2P3/1PN1B3/1P3QB1/1K1R3r w - -", (__actual, __expected) => __actual === __expected)
  }

  testInvalidCastlingRights(): void {
    // KQkq is not valid in this standard chess position.
    let board = new chess.Board("1r2k3/8/8/8/8/8/8/R3KR2 w KQkq - 0 1")
    this.assertEqualUsing(board.status(), chess.STATUS_BAD_CASTLING_RIGHTS, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), "1r2k3/8/8/8/8/8/8/R3KR2 w Q - 0 1", (__actual, __expected) => __actual === __expected)
    this.assertTrue(board.hasQueensideCastlingRights(chess.WHITE))
    this.assertFalse(board.hasKingsideCastlingRights(chess.WHITE))
    this.assertFalse(board.hasQueensideCastlingRights(chess.BLACK))
    this.assertFalse(board.hasKingsideCastlingRights(chess.BLACK))

    board = new chess.Board("4k2r/8/8/8/8/8/8/R1K5 w KQkq - 0 1", { chess960: true })
    this.assertEqualUsing(board.status(), chess.STATUS_BAD_CASTLING_RIGHTS, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), "4k2r/8/8/8/8/8/8/R1K5 w Qk - 0 1", (__actual, __expected) => __actual === __expected)

    board = new chess.Board("1r2k3/8/1p6/8/8/5P2/8/1R2KR2 w KQkq - 0 1", { chess960: true })
    this.assertEqualUsing(board.status(), chess.STATUS_BAD_CASTLING_RIGHTS, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), "1r2k3/8/1p6/8/8/5P2/8/1R2KR2 w KQq - 0 1", (__actual, __expected) => __actual === __expected)
  }

  testNinesixtyDifferentKingAndRookFile(): void {
    // Theoretically, this position (with castling rights) can not be reached
    // with a series of legal moves from one of the 960 starting positions.
    // Decision: We don't care, neither do Stockfish or lichess.org.
    const fen = "1r1k1r2/5p2/8/8/8/8/3N4/R5KR b KQkq - 0 1"
    const board = new chess.Board(fen, { chess960: true })
    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)
  }

  testNinesixtyPreventedCastle(): void {
    const board = new chess.Board("4k3/8/8/1b6/8/8/8/5RKR w KQ - 0 1", { chess960: true })
    this.assertFalse(board.isLegal(chess.Move.fromUci("g1f1")))
  }

  testFindMove(): void {
    const board = new chess.Board("4k3/1P6/8/8/8/8/3P4/4K2R w K - 0 1")

    // Pawn moves.
    this.assertEqualUsing(board.findMove(chess.D2, chess.D4), chess.Move.fromUci("d2d4"), (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(board.findMove(chess.B7, chess.B8), chess.Move.fromUci("b7b8q"), (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(board.findMove(chess.B7, chess.B8, chess.KNIGHT), chess.Move.fromUci("b7b8n"), (__actual, __expected) => __actual.equals(__expected))

    // Illegal moves.
    this.assertRaises(chess.IllegalMoveError, () => {
      board.findMove(chess.D2, chess.D8)
    })
    this.assertRaises(chess.IllegalMoveError, () => {
      board.findMove(chess.E1, chess.A1)
    })

    // Castling.
    this.assertEqualUsing(board.findMove(chess.E1, chess.G1), chess.Move.fromUci("e1g1"), (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(board.findMove(chess.E1, chess.H1), chess.Move.fromUci("e1g1"), (__actual, __expected) => __actual.equals(__expected))
    ;((__newValue, __receiver) => { __receiver.chess960 = __newValue; })(true, board)
    this.assertEqualUsing(board.findMove(chess.E1, chess.H1), chess.Move.fromUci("e1h1"), (__actual, __expected) => __actual.equals(__expected))
  }

  testCleanCastlingRights(): void {
    const board = new chess.Board()
    board.setBoardFen("k6K/8/8/pppppppp/8/8/8/QqQq4")
    this.assertEqualUsing(board.cleanCastlingRights(), chess.BB_EMPTY, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), "k6K/8/8/pppppppp/8/8/8/QqQq4 w - - 0 1", (__actual, __expected) => __actual === __expected)
    board.pushSan("Qxc5")
    this.assertEqualUsing(board.cleanCastlingRights(), chess.BB_EMPTY, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), "k6K/8/8/ppQppppp/8/8/8/Qq1q4 b - - 0 1", (__actual, __expected) => __actual === __expected)
  }

  testPromotionWithCheck(): void {
    let board = new chess.Board("8/6P1/2p5/1Pqk4/6P1/2P1RKP1/4P1P1/8 w - - 0 1")
    board.push(chess.Move.fromUci("g7g8q"))
    this.assertTrue(board.isCheck())
    this.assertEqualUsing(board.fen(), "6Q1/8/2p5/1Pqk4/6P1/2P1RKP1/4P1P1/8 b - - 0 1", (__actual, __expected) => __actual === __expected)

    board = new chess.Board("8/8/8/3R1P2/8/2k2K2/3p4/r7 b - - 0 82")
    board.pushSan("d1=Q+")
    this.assertEqualUsing(board.fen(), "8/8/8/3R1P2/8/2k2K2/8/r2q4 w - - 0 83", (__actual, __expected) => __actual === __expected)
  }

  testAmbiguousMove(): void {
    const board = new chess.Board("8/8/1n6/3R1P2/1n6/2k2K2/3p4/r6r b - - 0 82")
    this.assertRaises(chess.AmbiguousMoveError, () => {
      board.parseSan("Rf1")
    })
    this.assertRaises(chess.AmbiguousMoveError, () => {
      board.parseSan("Nd5")
    })
  }

  testScholarsMate(): void {
    const board = new chess.Board()

    const e4 = chess.Move.fromUci("e2e4")
    this.assertContainsUsing(e4, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(e4)

    const e5 = chess.Move.fromUci("e7e5")
    this.assertContainsUsing(e5, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(e5)

    const Qf3 = chess.Move.fromUci("d1f3")
    this.assertContainsUsing(Qf3, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(Qf3)

    const Nc6 = chess.Move.fromUci("b8c6")
    this.assertContainsUsing(Nc6, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(Nc6)

    const Bc4 = chess.Move.fromUci("f1c4")
    this.assertContainsUsing(Bc4, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(Bc4)

    const Rb8 = chess.Move.fromUci("a8b8")
    this.assertContainsUsing(Rb8, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(Rb8)

    this.assertFalse(board.isCheck())
    this.assertFalse(board.isCheckmate())
    this.assertFalse(board.isGameOver())
    this.assertFalse(board.isStalemate())

    const Qf7Mate = chess.Move.fromUci("f3f7")
    this.assertContainsUsing(Qf7Mate, board.legalMoves, (__container, __member) => __container.contains(__member))
    board.push(Qf7Mate)

    this.assertTrue(board.isCheck())
    this.assertTrue(board.isCheckmate())
    this.assertTrue(board.isGameOver())
    this.assertTrue(board.isGameOver({ claimDraw: true }))
    this.assertFalse(board.isStalemate())

    this.assertEqualUsing(board.fen(), "1rbqkbnr/pppp1Qpp/2n5/4p3/2B1P3/8/PPPP1PPP/RNB1K1NR b KQk - 0 4", (__actual, __expected) => __actual === __expected)
  }

  testResult(): void {
    // Undetermined.
    let board = new chess.Board()
    this.assertEqualUsing(board.result({ claimDraw: true }), "*", (__actual, __expected) => __actual === __expected)

    // White checkmated.
    board = new chess.Board("rnb1kbnr/pppp1ppp/8/4p3/6Pq/5P2/PPPPP2P/RNBQKBNR w KQkq - 1 3")
    this.assertEqualUsing(board.result({ claimDraw: true }), "0-1", (__actual, __expected) => __actual === __expected)

    // Stalemate.
    board = new chess.Board("7K/7P/7k/8/6q1/8/8/8 w - - 0 1")
    this.assertEqualUsing(board.result(), "1/2-1/2", (__actual, __expected) => __actual === __expected)

    // Insufficient material.
    board = new chess.Board("4k3/8/8/8/8/5B2/8/4K3 w - - 0 1")
    this.assertEqualUsing(board.result(), "1/2-1/2", (__actual, __expected) => __actual === __expected)

    // Fiftyseven-move rule.
    board = new chess.Board("4k3/8/6r1/8/8/8/2R5/4K3 w - - 369 1")
    this.assertEqualUsing(board.result(), "1/2-1/2", (__actual, __expected) => __actual === __expected)

    // Fifty-move rule.
    board = new chess.Board("4k3/8/6r1/8/8/8/2R5/4K3 w - - 120 1")
    this.assertEqualUsing(board.result(), "*", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.result({ claimDraw: true }), "1/2-1/2", (__actual, __expected) => __actual === __expected)
  }

  testSan(): void {
    // Castling with check.
    let fen = "rnbk1b1r/ppp2pp1/5n1p/4p1B1/2P5/2N5/PP2PPPP/R3KBNR w KQ - 0 7"
    let board = new chess.Board(fen)
    const longCastleCheck = chess.Move.fromUci("e1a1")
    this.assertEqualUsing(board.san(longCastleCheck), "O-O-O+", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)

    // En passant mate.
    fen = "6bk/7b/8/3pP3/8/8/8/Q3K3 w - d6 0 2"
    board = new chess.Board(fen)
    const fxe6MateEp = chess.Move.fromUci("e5d6")
    this.assertEqualUsing(board.san(fxe6MateEp), "exd6#", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)

    // Test disambiguation.
    fen = "N3k2N/8/8/3N4/N4N1N/2R5/1R6/4K3 w - - 0 1"
    board = new chess.Board(fen)
    this.assertEqualUsing(board.san(chess.Move.fromUci("e1f1")), "Kf1", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.san(chess.Move.fromUci("c3c2")), "Rcc2", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.san(chess.Move.fromUci("b2c2")), "Rbc2", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.san(chess.Move.fromUci("a4b6")), "N4b6", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.san(chess.Move.fromUci("h8g6")), "N8g6", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.san(chess.Move.fromUci("h4g6")), "Nh4g6", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)

    // Test a bug where shakmaty used overly specific disambiguation.
    fen = "8/2KN1p2/5p2/3N1B1k/5PNp/7P/7P/8 w - -"
    board = new chess.Board(fen)
    this.assertEqualUsing(board.san(chess.Move.fromUci("d5f6")), "N5xf6#", (__actual, __expected) => __actual === __expected)

    // Do not disambiguate illegal alternatives.
    fen = "8/8/8/R2nkn2/8/8/2K5/8 b - - 0 1"
    board = new chess.Board(fen)
    this.assertEqualUsing(board.san(chess.Move.fromUci("f5e3")), "Ne3+", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)

    // Promotion.
    fen = "7k/1p2Npbp/8/2P5/1P1r4/3b2QP/3q1pPK/2RB4 b - - 1 29"
    board = new chess.Board(fen)
    this.assertEqualUsing(board.san(chess.Move.fromUci("f2f1q")), "f1=Q", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.san(chess.Move.fromUci("f2f1n")), "f1=N+", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)
  }

  testLan(): void {
    // Normal moves always with origin square.
    let fen = "N3k2N/8/8/3N4/N4N1N/2R5/1R6/4K3 w - - 0 1"
    let board = new chess.Board(fen)
    this.assertEqualUsing(board.lan(chess.Move.fromUci("e1f1")), "Ke1-f1", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.lan(chess.Move.fromUci("c3c2")), "Rc3-c2", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.lan(chess.Move.fromUci("a4c5")), "Na4-c5", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)

    // Normal capture.
    fen = "rnbq1rk1/ppp1bpp1/4pn1p/3p2B1/2PP4/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 7"
    board = new chess.Board(fen)
    this.assertEqualUsing(board.lan(chess.Move.fromUci("g5f6")), "Bg5xf6", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)

    // Pawn captures and moves.
    fen = "6bk/7b/8/3pP3/8/8/8/Q3K3 w - d6 0 2"
    board = new chess.Board(fen)
    this.assertEqualUsing(board.lan(chess.Move.fromUci("e5d6")), "e5xd6#", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.lan(chess.Move.fromUci("e5e6")), "e5-e6+", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)
  }

  testSanNewline(): void {
    const board = new chess.Board("rnbqk2r/ppppppbp/5np1/8/8/5NP1/PPPPPPBP/RNBQK2R w KQkq - 2 4")
    this.assertRaises(chess.InvalidMoveError, () => {
      board.parseSan("O-O\n")
    })
    this.assertRaises(chess.InvalidMoveError, () => {
      board.parseSan("Nc3\n")
    })
  }

  testPawnCaptureSanWithoutFile(): void {
    let board = new chess.Board("2rq1rk1/pb2bppp/1p2p3/n1ppPn2/2PP4/PP3N2/1B1NQPPP/RB3RK1 b - - 4 13")
    this.assertRaises(chess.IllegalMoveError, () => {
      board.parseSan("c4")
    })
    board = new chess.Board("4k3/8/8/4Pp2/8/8/8/4K3 w - f6 0 2")
    this.assertRaises(chess.IllegalMoveError, () => {
      board.parseSan("f6")
    })
  }

  testVariationSan(): void {
    let board = new chess.Board()
    this.assertEqualUsing("1. e4 e5 2. Nf3", board.variationSan(Array.from(["e2e4", "e7e5", "g1f3"], __mItem => chess.Move.fromUci(__mItem))), (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing("1. e4 e5 2. Nf3 Nc6 3. Bb5 a6", board.variationSan(Array.from(["e2e4", "e7e5", "g1f3", "b8c6", "f1b5", "a7a6"], __mItem2 => chess.Move.fromUci(__mItem2))), (__actual, __expected) => __actual === __expected)

    const fen = "rn1qr1k1/1p2bppp/p3p3/3pP3/P2P1B2/2RB1Q1P/1P3PP1/R5K1 w - - 0 19"
    board = new chess.Board(fen)
    const variation = ["d3h7", "g8h7", "f3h5", "h7g8", "c3g3", "e7f8", "f4g5", "e8e7", "g5f6", "b8d7", "h5h6", "d7f6", "e5f6", "g7g6", "f6e7", "f8e7"]
    const varW = board.variationSan(Array.from(variation, __mItem3 => chess.Move.fromUci(__mItem3)))
    this.assertEqualUsing("19. Bxh7+ Kxh7 20. Qh5+ Kg8 21. Rg3 Bf8 22. Bg5 Re7 23. Bf6 Nd7 24. Qh6 Nxf6 25. exf6 g6 26. fxe7 Bxe7", varW, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(fen, board.fen(), (__actual, __expected) => __actual === __expected, "Board unchanged by variation_san")
    board.push(chess.Move.fromUci(((__sequence, __index) => { const __normalizedIndex = __index < 0 ? __sequence.length + __index : __index; if (__normalizedIndex < 0 || __normalizedIndex >= __sequence.length) throw new RangeError("array index out of range"); const __removed = __sequence.splice(__normalizedIndex, 1); return __removed[0]; })(variation, 0)))
    const varB = board.variationSan(Array.from(variation, __mItem4 => chess.Move.fromUci(__mItem4)))
    this.assertEqualUsing("19...Kxh7 20. Qh5+ Kg8 21. Rg3 Bf8 22. Bg5 Re7 23. Bf6 Nd7 24. Qh6 Nxf6 25. exf6 g6 26. fxe7 Bxe7", varB, (__actual, __expected) => __actual === __expected)

    const illegalVariation = ["d3h7", "g8h7", "f3h6", "h7g8"]
    board = new chess.Board(fen)
    const err = this.captureRaises(chess.IllegalMoveError, () => {
      board.variationSan(Array.from(illegalVariation, __mItem5 => chess.Move.fromUci(__mItem5)))
    })
    const message = err.message
    this.assertContainsUsing("illegal move", ((__lowerValue) => { if (!/^[\x00-\x7F]*$/.test(__lowerValue)) throw new RangeError("lower() supports only ASCII strings because Python and TypeScript Unicode case mappings are not version-stable"); return __lowerValue.toLowerCase(); })(message), (__container, __member) => __container.includes(__member), `Error [${message}] mentions illegal move`)
    this.assertContainsUsing("f3h6", message, (__container, __member) => __container.includes(__member), `Illegal move f3h6 appears in message [${message}]`)
  }

  testMoveStackUsage(): void {
    const board = new chess.Board()
    board.pushUci("d2d4")
    board.pushUci("d7d5")
    board.pushUci("g1f3")
    board.pushUci("c8f5")
    board.pushUci("e2e3")
    board.pushUci("e7e6")
    board.pushUci("f1d3")
    board.pushUci("f8d6")
    board.pushUci("e1h1")
    const san = new chess.Board().variationSan(board.moveStack)
    this.assertEqualUsing(san, "1. d4 d5 2. Nf3 Bf5 3. e3 e6 4. Bd3 Bd6 5. O-O", (__actual, __expected) => __actual === __expected)
  }

  testIsLegalMove(): void {
    const fen = "3k4/6P1/7P/8/K7/8/8/4R3 w - - 0 1"
    const board = new chess.Board(fen)

    // Legal moves: Rg1, g8=R+.
    this.assertContainsUsing(chess.Move.fromUci("e1g1"), board.legalMoves, (__container, __member) => __container.contains(__member))
    this.assertContainsUsing(chess.Move.fromUci("g7g8r"), board.legalMoves, (__container, __member) => __container.contains(__member))

    // Impossible promotion: Kb5, h7.
    this.assertNotContainsUsing(chess.Move.fromUci("a5b5q"), board.legalMoves, (__container, __member) => __container.contains(__member))
    this.assertNotContainsUsing(chess.Move.fromUci("h6h7n"), board.legalMoves, (__container, __member) => __container.contains(__member))

    // Missing promotion.
    this.assertNotContainsUsing(chess.Move.fromUci("g7g8"), board.legalMoves, (__container, __member) => __container.contains(__member))

    // Promote to pawn or king.
    this.assertFalse(board.isLegal(chess.Move.fromUci("g7g8p")))
    this.assertFalse(board.isPseudoLegal(chess.Move.fromUci("g7g8p")))
    this.assertFalse(board.isLegal(chess.Move.fromUci("g7g8k")))
    this.assertFalse(board.isPseudoLegal(chess.Move.fromUci("g7g8k")))

    this.assertEqualUsing(board.fen(), fen, (__actual, __expected) => __actual === __expected)
  }

  testMoveCount(): void {
    const board = new chess.Board("1N2k3/P7/8/8/3n4/8/2PP4/R3K2R w KQ - 0 1")
    this.assertEqualUsing(board.pseudoLegalMoves.count(), ((__leftNumber, __rightNumber) => { const __numberResult = __leftNumber + __rightNumber; if (!Number.isSafeInteger(__numberResult)) throw new RangeError("integer result is outside TypeScript's safe range"); return __numberResult; })(((__leftNumber, __rightNumber) => { const __numberResult = __leftNumber + __rightNumber; if (!Number.isSafeInteger(__numberResult)) throw new RangeError("integer result is outside TypeScript's safe range"); return __numberResult; })(((__leftNumber, __rightNumber) => { const __numberResult = __leftNumber + __rightNumber; if (!Number.isSafeInteger(__numberResult)) throw new RangeError("integer result is outside TypeScript's safe range"); return __numberResult; })(((__leftNumber, __rightNumber) => { const __numberResult = __leftNumber + __rightNumber; if (!Number.isSafeInteger(__numberResult)) throw new RangeError("integer result is outside TypeScript's safe range"); return __numberResult; })(((__leftNumber, __rightNumber) => { const __numberResult = __leftNumber + __rightNumber; if (!Number.isSafeInteger(__numberResult)) throw new RangeError("integer result is outside TypeScript's safe range"); return __numberResult; })(((__leftNumber, __rightNumber) => { const __numberResult = __leftNumber + __rightNumber; if (!Number.isSafeInteger(__numberResult)) throw new RangeError("integer result is outside TypeScript's safe range"); return __numberResult; })(8, 4), 3), 2), 1), 6), 9), (__actual, __expected) => __actual === __expected)
  }
}

registerTestCase('BoardTestCase', BoardTestCase, {
  lines: {
    testDefaultPosition: 212,
    testEmpty: 218,
    testPly: 223,
    testFromEpd: 235,
    testSetFenAsEpd: 1151,
    testMoveMaking: 241,
    testFen: 247,
    testXfen: 258,
    testFenEnPassant: 290,
    testGetSet: 296,
    testColorAt: 316,
    testPawnCaptures: 322,
    testPawnMoveGeneration: 337,
    testSingleStepPawnMove: 341,
    testCastling: 350,
    testCastlingSan: 392,
    testNinesixtyCastling: 400,
    testHsideRookBlocksAsideCastling: 451,
    testSelectiveCastling: 459,
    testCastlingRightNotDestroyedBug: 469,
    testInvalidCastlingRights: 476,
    testNinesixtyDifferentKingAndRookFile: 494,
    testNinesixtyPreventedCastle: 502,
    testFindMove: 506,
    testCleanCastlingRights: 526,
    testPromotionWithCheck: 593,
    testAmbiguousMove: 603,
    testScholarsMate: 610,
    testResult: 654,
    testSan: 680,
    testLan: 724,
    testSanNewline: 746,
    testPawnCaptureSanWithoutFile: 753,
    testVariationSan: 761,
    testMoveStackUsage: 796,
    testIsLegalMove: 810,
    testMoveCount: 833,
  },
})

/** Generated directly from the frozen python-chess syntax tree. */
class LegalMoveGeneratorTestCase extends TestCase {
  testListConversion(): void {
    this.assertEqualUsing(Array.from(new chess.Board().legalMoves).length, 20, (__actual, __expected) => __actual === __expected)
  }

  testNonzero(): void {
    this.assertTrue(new chess.Board().legalMoves.bool())
    this.assertTrue(new chess.Board().pseudoLegalMoves.bool())

    const caroKannMate = new chess.Board("r1bqkb1r/pp1npppp/2pN1n2/8/3P4/8/PPP1QPPP/R1B1KBNR b KQkq - 4 6")
    this.assertFalse(caroKannMate.legalMoves.bool())
    this.assertTrue(caroKannMate.pseudoLegalMoves.bool())
  }

  testStringConversion(): void {
    const board = new chess.Board("r3k1nr/ppq1pp1p/2p3p1/8/1PPR4/2N5/P3QPPP/5RK1 b kq b3 0 16")

    this.assertContainsUsing("Qxh2+", board.legalMoves.toString(), (__container, __member) => __container.includes(__member))
    this.assertContainsUsing("Qxh2+", board.legalMoves.toString(), (__container, __member) => __container.includes(__member))

    this.assertContainsUsing("Qxh2+", board.pseudoLegalMoves.toString(), (__container, __member) => __container.includes(__member))
    this.assertContainsUsing("Qxh2+", board.pseudoLegalMoves.toString(), (__container, __member) => __container.includes(__member))
    this.assertContainsUsing("e8d7", board.pseudoLegalMoves.toString(), (__container, __member) => __container.includes(__member))
    this.assertContainsUsing("e8d7", board.pseudoLegalMoves.toString(), (__container, __member) => __container.includes(__member))
  }

  testTraverseOnce(): void {
    class MockBoard {
      declare traversals: number
      constructor() {
        ;((__newValue, __receiver) => { __receiver.traversals = __newValue; })(0, this)
      }
      *generateLegalMoves() {
        this.traversals = ((__leftNumber, __rightNumber) => { const __numberResult = __leftNumber + __rightNumber; if (!Number.isSafeInteger(__numberResult)) throw new RangeError("integer result is outside TypeScript's safe range"); return __numberResult; })(this.traversals, 1)
        return
        yield undefined
      }
    }

    const board = new MockBoard()
    const gen = new chess.LegalMoveGenerator((board as /* protocol-adapter: legal-move-generator-board */ unknown as /* protocol-adapter: legal-move-generator-board */ chess.Board))
    Array.from(gen)
    this.assertEqualUsing(board.traversals, 1, (__actual, __expected) => __actual === __expected)
  }
}

registerTestCase('LegalMoveGeneratorTestCase', LegalMoveGeneratorTestCase, {
  lines: {
    testListConversion: 1726,
    testNonzero: 1729,
    testStringConversion: 1737,
    testTraverseOnce: 1748,
  },
})

/** Generated directly from the frozen python-chess syntax tree. */
class BaseBoardTestCase extends TestCase {
  testSetPieceMap(): void {
    const a = chess.BaseBoard.empty()
    const b = new chess.BaseBoard()
    a.setPieceMap(b.pieceMap())
    this.assertEqualUsing(a, b, (__actual, __expected) => __actual.equals(__expected))
    a.setPieceMap(new Map())
    this.assertNotEqualUsing(a, b, (__actual, __expected) => __actual.equals(__expected))
  }
}

registerTestCase('BaseBoardTestCase', BaseBoardTestCase, {
  lines: {
    testSetPieceMap: 1766,
  },
})

/** Generated directly from the frozen python-chess syntax tree. */
class SquareSetTestCase extends TestCase {
  testEquality(): void {
    const a1 = new chess.SquareSet(chess.BB_RANK_4)
    const a2 = new chess.SquareSet(chess.BB_RANK_4)
    const b1 = new chess.SquareSet((chess.BB_RANK_5 | chess.BB_RANK_6))
    const b2 = new chess.SquareSet((chess.BB_RANK_5 | chess.BB_RANK_6))

    this.assertEqualUsing(a1, a2, (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(b1, b2, (__actual, __expected) => __actual.equals(__expected))
    this.assertFalse(!(((__left, __right) => __left.equals(__right))(a1, a2)))
    this.assertFalse(!(((__left, __right) => __left.equals(__right))(b1, b2)))

    this.assertNotEqualUsing(a1, b1, (__actual, __expected) => __actual.equals(__expected))
    this.assertNotEqualUsing(a2, b2, (__actual, __expected) => __actual.equals(__expected))
    this.assertFalse(((__left, __right) => __left.equals(__right))(a1, b1))
    this.assertFalse(((__left, __right) => __left.equals(__right))(a2, b2))

    this.assertEqualUsing(new chess.SquareSet(chess.BB_ALL), chess.BB_ALL, (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(chess.BB_ALL, new chess.SquareSet(chess.BB_ALL), (__actual, __expected) => __expected.equals(__actual))

    this.assertEqualUsing(new chess.SquareSet(new chess.SquareSet(BigInt(999))).int(), 999, (__actual, __expected) => __actual === BigInt(__expected))
    this.assertEqualUsing(new chess.SquareSet([chess.B8]), chess.BB_B8, (__actual, __expected) => __actual.equals(__expected))
  }

  testStringConversion(): void {
    const expected = ". . . . . . . 1\n. 1 . . . . . .\n. . . . . . . .\n. . . . . . . .\n. . . . . . . .\n. . . . . . . .\n. . . . . . . .\n1 1 1 1 1 1 1 1"

    const bb = new chess.SquareSet(((chess.BB_H8 | chess.BB_B7) | chess.BB_RANK_1))
    this.assertEqualUsing(bb.toString(), expected, (__actual, __expected) => __actual === __expected)
  }

  testIter(): void {
    const bb = new chess.SquareSet((chess.BB_G7 | chess.BB_G8))
    this.assertEqualUsing(Array.from(bb.iter()), [chess.G7, chess.G8], (__actual, __expected) => __actual.length === __expected.length && __actual.every((__value0, __index0) => __expected.slice(__index0, __index0 + 1).some(__expected0 => __value0 === __expected0)))
  }

  testReversed(): void {
    const bb = new chess.SquareSet((((chess.BB_A1 | chess.BB_B1) | chess.BB_A7) | chess.BB_E1))
    this.assertEqualUsing(Array.from(bb.reversed()), [chess.A7, chess.E1, chess.B1, chess.A1], (__actual, __expected) => __actual.length === __expected.length && __actual.every((__value0, __index0) => __expected.slice(__index0, __index0 + 1).some(__expected0 => __value0 === __expected0)))
  }

  testArithmetic(): void {
    this.assertEqualUsing(new chess.SquareSet(chess.BB_RANK_2).and(chess.BB_FILE_D), chess.BB_D2, (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(new chess.SquareSet(chess.BB_ALL).xor(chess.BB_EMPTY), chess.BB_ALL, (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(new chess.SquareSet(chess.BB_C1).or(chess.BB_FILE_C), chess.BB_FILE_C, (__actual, __expected) => __actual.equals(__expected))

    let bb = new chess.SquareSet(chess.BB_EMPTY)
    bb.ixor(chess.BB_ALL)
    this.assertEqualUsing(bb, chess.BB_ALL, (__actual, __expected) => __actual.equals(__expected))
    bb.iand(chess.BB_E4)
    this.assertEqualUsing(bb, chess.BB_E4, (__actual, __expected) => __actual.equals(__expected))
    bb.ior(chess.BB_RANK_4)
    this.assertEqualUsing(bb, chess.BB_RANK_4, (__actual, __expected) => __actual.equals(__expected))

    this.assertEqualUsing(new chess.SquareSet(chess.BB_F3).lshift(BigInt(1)), chess.BB_G3, (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(new chess.SquareSet(chess.BB_C8).rshift(BigInt(2)), chess.BB_A8, (__actual, __expected) => __actual.equals(__expected))

    bb = new chess.SquareSet(chess.BB_D1)
    bb.ilshift(BigInt(1))
    this.assertEqualUsing(bb, chess.BB_E1, (__actual, __expected) => __actual.equals(__expected))
    bb.irshift(BigInt(2))
    this.assertEqualUsing(bb, chess.BB_C1, (__actual, __expected) => __actual.equals(__expected))
  }

  testImmutableSetOperations(): void {
    const examples = [chess.BB_EMPTY, chess.BB_A1, chess.BB_A2, chess.BB_RANK_1, chess.BB_RANK_2, chess.BB_FILE_A, chess.BB_FILE_E]

    for (let a of examples) {
      this.assertEqualUsing(new chess.SquareSet(a).copy(), a, (__actual, __expected) => __actual.equals(__expected))
    }

    for (let a of examples) {
      let __aRebound = new chess.SquareSet(a)
      for (let b of examples) {
        let __bRebound = new chess.SquareSet(b)
        this.assertEqualUsing(((__leftSet, __rightSet) => Array.from(__leftSet).every(__setValue => !__rightSet.has(__setValue)))(new Set(Array.from(__aRebound.iter())), new Set(Array.from(__bRebound.iter()))), __aRebound.isdisjoint(__bRebound), (__actual, __expected) => __actual === __expected)
        this.assertEqualUsing(((__leftSet, __rightSet) => Array.from(__leftSet).every(__setValue => __rightSet.has(__setValue)))(new Set(Array.from(__aRebound.iter())), new Set(Array.from(__bRebound.iter()))), __aRebound.issubset(__bRebound), (__actual, __expected) => __actual === __expected)
        this.assertEqualUsing(((__leftSet, __rightSet) => Array.from(__rightSet).every(__setValue => __leftSet.has(__setValue)))(new Set(Array.from(__aRebound.iter())), new Set(Array.from(__bRebound.iter()))), __aRebound.issuperset(__bRebound), (__actual, __expected) => __actual === __expected)
        this.assertEqualUsing(((__leftSet, __rightSet) => new Set([...__leftSet, ...__rightSet]))(new Set(Array.from(__aRebound.iter())), new Set(Array.from(__bRebound.iter()))), new Set(Array.from(__aRebound.union(__bRebound).iter())), (__actual, __expected) => __actual.size === __expected.size && Array.from(__actual).every(__setValue => __expected.has(__setValue)))
        this.assertEqualUsing(((__leftSet, __rightSet) => new Set(Array.from(__leftSet).filter(__setValue => __rightSet.has(__setValue))))(new Set(Array.from(__aRebound.iter())), new Set(Array.from(__bRebound.iter()))), new Set(Array.from(__aRebound.intersection(__bRebound).iter())), (__actual, __expected) => __actual.size === __expected.size && Array.from(__actual).every(__setValue => __expected.has(__setValue)))
        this.assertEqualUsing(((__leftSet, __rightSet) => new Set(Array.from(__leftSet).filter(__setValue => !__rightSet.has(__setValue))))(new Set(Array.from(__aRebound.iter())), new Set(Array.from(__bRebound.iter()))), new Set(Array.from(__aRebound.difference(__bRebound).iter())), (__actual, __expected) => __actual.size === __expected.size && Array.from(__actual).every(__setValue => __expected.has(__setValue)))
        this.assertEqualUsing(((__leftSet, __rightSet) => new Set([...Array.from(__leftSet).filter(__leftValue => !__rightSet.has(__leftValue)), ...Array.from(__rightSet).filter(__rightValue => !__leftSet.has(__rightValue))]))(new Set(Array.from(__aRebound.iter())), new Set(Array.from(__bRebound.iter()))), new Set(Array.from(__aRebound.symmetricDifference(__bRebound).iter())), (__actual, __expected) => __actual.size === __expected.size && Array.from(__actual).every(__setValue => __expected.has(__setValue)))
      }
    }
  }

  testMutableSetOperations(): void {
    const squares = new chess.SquareSet(chess.BB_A1)
    squares.update(chess.BB_FILE_H)
    this.assertEqualUsing(squares, (chess.BB_A1 | chess.BB_FILE_H), (__actual, __expected) => __actual.equals(__expected))

    squares.intersectionUpdate(chess.BB_RANK_8)
    this.assertEqualUsing(squares, chess.BB_H8, (__actual, __expected) => __actual.equals(__expected))

    squares.differenceUpdate(chess.BB_A1)
    this.assertEqualUsing(squares, chess.BB_H8, (__actual, __expected) => __actual.equals(__expected))

    squares.symmetricDifferenceUpdate(chess.BB_A1)
    this.assertEqualUsing(squares, (chess.BB_A1 | chess.BB_H8), (__actual, __expected) => __actual.equals(__expected))

    squares.add(chess.A3)
    this.assertEqualUsing(squares, ((chess.BB_A1 | chess.BB_A3) | chess.BB_H8), (__actual, __expected) => __actual.equals(__expected))

    squares.remove(chess.H8)
    this.assertEqualUsing(squares, (chess.BB_A1 | chess.BB_A3), (__actual, __expected) => __actual.equals(__expected))

    this.assertRaises(chess.KeyError, () => {
      squares.remove(chess.H8)
    })

    squares.discard(chess.H8)

    squares.discard(chess.A1)
    this.assertEqualUsing(squares, chess.BB_A3, (__actual, __expected) => __actual.equals(__expected))

    squares.clear()
    this.assertEqualUsing(squares, chess.BB_EMPTY, (__actual, __expected) => __actual.equals(__expected))

    this.assertRaises(chess.KeyError, () => {
      squares.pop()
    })

    squares.add(chess.C7)
    this.assertEqualUsing(squares.pop(), chess.C7, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(squares, chess.BB_EMPTY, (__actual, __expected) => __actual.equals(__expected))
  }

  testFromSquare(): void {
    this.assertEqualUsing(chess.SquareSet.fromSquare(chess.H5), chess.BB_H5, (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(chess.SquareSet.fromSquare(chess.C2), chess.BB_C2, (__actual, __expected) => __actual.equals(__expected))
  }

  testCarryRippler(): void {
    this.assertEqualUsing(((__iterable) => { let __total = 0; for (const __value of __iterable) { __total = (() => { const __numberResult = __total + __value; if (!Number.isSafeInteger(__numberResult)) throw new RangeError("integer result is outside TypeScript's safe range"); return __numberResult; })(); } return __total; })(((__iterable) => (function* () { for (const ___Item of __iterable) { yield 1; } })())(new chess.SquareSet(chess.BB_D1).carryRippler())), ((__base, __exponent) => { const __numberResult = __base ** __exponent; if (!Number.isSafeInteger(__numberResult)) throw new RangeError("integer result is outside TypeScript's safe range"); return __numberResult; })(2, 1), (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(((__iterable) => { let __total = 0; for (const __value of __iterable) { __total = (() => { const __numberResult = __total + __value; if (!Number.isSafeInteger(__numberResult)) throw new RangeError("integer result is outside TypeScript's safe range"); return __numberResult; })(); } return __total; })(((__iterable) => (function* () { for (const ___Item2 of __iterable) { yield 1; } })())(new chess.SquareSet(chess.BB_FILE_B).carryRippler())), ((__base, __exponent) => { const __numberResult = __base ** __exponent; if (!Number.isSafeInteger(__numberResult)) throw new RangeError("integer result is outside TypeScript's safe range"); return __numberResult; })(2, 8), (__actual, __expected) => __actual === __expected)
  }

  testMirror(): void {
    this.assertEqualUsing(new chess.SquareSet(0x00a2_0900_0004_a600n).mirror(), 0x00a6_0400_0009_a200n, (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(new chess.SquareSet(0x1e22_2212_0e0a_1222n).mirror(), 0x2212_0a0e_1222_221en, (__actual, __expected) => __actual.equals(__expected))
  }

  testFlip(): void {
    this.assertEqualUsing(chess.flipVertical(chess.BB_ALL), chess.BB_ALL, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.flipHorizontal(chess.BB_ALL), chess.BB_ALL, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.flipDiagonal(chess.BB_ALL), chess.BB_ALL, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.flipAntiDiagonal(chess.BB_ALL), chess.BB_ALL, (__actual, __expected) => __actual === __expected)

    const s = new chess.SquareSet(0x1e22_2212_0e0a_1222n) // Letter R
    this.assertEqualUsing(chess.flipVertical(s.int()), 0x2212_0a0e_1222_221en, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.flipHorizontal(s.int()), 0x7844_4448_7050_4844n, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(chess.flipDiagonal(s.int()), 107282050907904, (__actual, __expected) => __actual === BigInt(__expected))
    this.assertEqualUsing(chess.flipAntiDiagonal(s.int()), 0x00ff_1131_4986_0000n, (__actual, __expected) => __actual === __expected)
  }

  testLenOfComplenent(): void {
    let squares = new chess.SquareSet(~(chess.BB_ALL))
    this.assertEqualUsing(squares.length(), 0, (__actual, __expected) => __actual === __expected)

    squares = new chess.SquareSet(chess.BB_BACKRANKS).invert()
    this.assertEqualUsing(squares.length(), 48, (__actual, __expected) => __actual === __expected)
  }

  testIntConversion(): void {
    this.assertEqualUsing(new chess.SquareSet(chess.BB_CENTER).int(), 103481868288, (__actual, __expected) => __actual === BigInt(__expected))
    this.assertEqualUsing(("0x" + new chess.SquareSet(chess.BB_CENTER).int().toString(16)), "0x1818000000", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(("0b" + new chess.SquareSet(chess.BB_CENTER).int().toString(2)), "0b1100000011000000000000000000000000000", (__actual, __expected) => __actual === __expected)
  }

  testTolist(): void {
    this.assertEqualUsing(((__sequence, __expected) => Array.from(__sequence).filter(__item => __item === __expected).length)(new chess.SquareSet(chess.BB_LIGHT_SQUARES).tolist(), true), 32, (__actual, __expected) => __actual === __expected)
  }

  testFlipDucktyping(): void {
    const bb = 0x1e22_2212_0e0a_1222n
    const squares = new chess.SquareSet(bb)
    for (let f of [chess.flipVertical, chess.flipHorizontal, chess.flipDiagonal, chess.flipAntiDiagonal]) {
      this.assertEqualUsing(f(squares.int()), f(bb), (__actual, __expected) => __actual === __expected)
      this.assertEqualUsing(squares.int(), bb, (__actual, __expected) => __actual === __expected) // Not mutated
    }
  }
}

registerTestCase('SquareSetTestCase', SquareSetTestCase, {
  lines: {
    testEquality: 1777,
    testStringConversion: 1799,
    testIter: 1813,
    testReversed: 1817,
    testArithmetic: 1821,
    testImmutableSetOperations: 1843,
    testMutableSetOperations: 1869,
    testFromSquare: 1907,
    testCarryRippler: 1911,
    testMirror: 1915,
    testFlip: 1919,
    testLenOfComplenent: 1931,
    testIntConversion: 1938,
    testTolist: 1943,
    testFlipDucktyping: 1946,
  },
})

/** Generated directly from the frozen python-chess syntax tree. */
class PgnTestCase extends TestCase {
  testExporter(): void {
    const game = new pgnModule.Game()
    ;((__newValue, __receiver) => { __receiver.comment = __newValue; })("Test game:", game)
    ;((__newValue, __headers, __key) => __headers.set(__key, __newValue))("*", game.headers, "Result")
    ;((__newValue, __headers, __key) => __headers.set(__key, __newValue))("This is a very long header, much wider than the 80 columns that PGNs are formatted with by default", game.headers, "VeryLongHeader")

    const e4 = game.addVariation(game.board().parseSan("e4"))
    ;((__newValue, __receiver) => { __receiver.comment = __newValue; })("Scandinavian Defense:", e4)

    const e4D5 = e4.addVariation(e4.board().parseSan("d5"))

    const e4H5 = e4.addVariation(e4.board().parseSan("h5"))
    e4H5.nags.add(pgnModule.NAG_MISTAKE)
    ;((__newValue, __receiver) => { __receiver.startingComment = __newValue; })("This", e4H5)
    ;((__newValue, __receiver) => { __receiver.comment = __newValue; })("is nonsense", e4H5)

    const e4E5 = e4.addVariation(e4.board().parseSan("e5"))
    const e4E5_Qf3 = e4E5.addVariation(e4E5.board().parseSan("Qf3"))
    e4E5_Qf3.nags.add(pgnModule.NAG_MISTAKE)

    const e4C5 = e4.addVariation(e4.board().parseSan("c5"))
    ;((__newValue, __receiver) => { __receiver.comment = __newValue; })("Sicilian", e4C5)

    const e4D5Exd5 = e4D5.addMainVariation(e4D5.board().parseSan("exd5"))
    ;((__newValue, __receiver) => { __receiver.comment = __newValue; })("Best", e4D5Exd5)

    // Test string exporter with various options.
    let exporter: pgnModule.StringExporter | pgnModule.FileExporter = new pgnModule.StringExporter({ headers: false, comments: false, variations: false })
    game.accept(exporter)
    this.assertEqualUsing(exporter.toString(), "1. e4 d5 2. exd5 *", (__actual, __expected) => __actual === __expected)

    exporter = new pgnModule.StringExporter({ headers: false, comments: false })
    game.accept(exporter)
    this.assertEqualUsing(exporter.toString(), "1. e4 d5 ( 1... h5 ) ( 1... e5 2. Qf3 ) ( 1... c5 ) 2. exd5 *", (__actual, __expected) => __actual === __expected)

    exporter = new pgnModule.StringExporter()
    game.accept(exporter)
    const pgn = "[Event \"?\"]\n[Site \"?\"]\n[Date \"????.??.??\"]\n[Round \"?\"]\n[White \"?\"]\n[Black \"?\"]\n[Result \"*\"]\n[VeryLongHeader \"This is a very long header, much wider than the 80 columns that PGNs are formatted with by default\"]\n\n{ Test game: } 1. e4 { Scandinavian Defense: } 1... d5 ( { This } 1... h5 $2\n{ is nonsense } ) ( 1... e5 2. Qf3 $2 ) ( 1... c5 { Sicilian } ) 2. exd5\n{ Best } *"
    this.assertEqualUsing(exporter.toString(), pgn, (__actual, __expected) => __actual === __expected)

    // Test file exporter.
    const virtualFile = new pgnModule.StringIO()
    exporter = new pgnModule.FileExporter(virtualFile)
    game.accept(exporter)
    this.assertEqualUsing(virtualFile.getValue(), (pgn + "\n\n"), (__actual, __expected) => __actual === __expected)
  }

  testPromoteToMain(): void {
    const e4 = chess.Move.fromUci("e2e4")
    const d4 = chess.Move.fromUci("d2d4")

    const node = new pgnModule.Game()
    node.addVariation(e4)
    node.addVariation(d4)
    this.assertEqualUsing(Array.from(((__iterable) => (function* () { for (const __variationItem of __iterable) { yield __variationItem.move; } })())(node.variations)), [e4, d4], (__actual, __expected) => __actual.length === __expected.length && __actual.every((__value0, __index0) => __expected.slice(__index0, __index0 + 1).some(__expected0 => __value0.equals(__expected0))))

    node.promoteToMain(d4)
    this.assertEqualUsing(Array.from(((__iterable) => (function* () { for (const __variationItem2 of __iterable) { yield __variationItem2.move; } })())(node.variations)), [d4, e4], (__actual, __expected) => __actual.length === __expected.length && __actual.every((__value0, __index0) => __expected.slice(__index0, __index0 + 1).some(__expected0 => __value0.equals(__expected0))))
  }

  testCommentAtEol(): void {
    const pgn = new pgnModule.StringIO("1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. c3 Nf6 5. d3 d6 6. Nbd2 a6 $6 (6... Bb6 $5 {\n/\\ Ne7, c6}) *")

    const game = pgnModule.readGame(pgn)

    // Seek the node after 6.Nbd2 and before 6...a6.
    let node: pgnModule.GameNode | null = game
    while ((((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(node).variations.length !== 0 && !(((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(node).hasVariation(chess.Move.fromUci("a7a6"))))) {
      node = ((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(node).getitem(0)
    }

    // Make sure the comment for the second variation is there.
    this.assertContainsUsing(5, ((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(node).getitem(1).nags, (__container, __member) => __container.has(__member))
    this.assertEqualUsing(((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(node).getitem(1).comment, "\n/\\ Ne7, c6", (__actual, __expected) => __actual === __expected)
  }

  testGameStartingComment(): void {
    let pgn = new pgnModule.StringIO("{ Game starting comment } 1. d3")
    let game: pgnModule.GameNode | null = pgnModule.readGame(pgn)
    this.assertEqualUsing(((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(game).comment, "Game starting comment", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(game).getitem(0).san(), "d3", (__actual, __expected) => __actual === __expected)

    pgn = new pgnModule.StringIO("{ Empty game, but has a comment }")
    game = pgnModule.readGame(pgn)
    this.assertEqualUsing(((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(game).comment, "Empty game, but has a comment", (__actual, __expected) => __actual === __expected)
  }

  testGameStartingVariation(): void {
    const pgn = new pgnModule.StringIO("{Start of game} 1. e4 ({Start of variation} 1. d4) 1... e5\n")

    const game = pgnModule.readGame(pgn)
    this.assertEqualUsing(((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(game).comment, "Start of game", (__actual, __expected) => __actual === __expected)

    let node: pgnModule.GameNode = ((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(game).getitem(0)
    this.assertEqualUsing(node.move, chess.Move.fromUci("e2e4"), (__actual, __expected) => __actual !== null && (__actual.equals(__expected)))
    this.assertFalse(node.comment.length !== 0)
    this.assertFalse(node.startingComment.length !== 0)

    node = ((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(game).getitem(1)
    this.assertEqualUsing(node.move, chess.Move.fromUci("d2d4"), (__actual, __expected) => __actual !== null && (__actual.equals(__expected)))
    this.assertFalse(node.comment.length !== 0)
    this.assertEqualUsing(node.startingComment, "Start of variation", (__actual, __expected) => __actual === __expected)
  }

  testTreeTraversal(): void {
    const game = new pgnModule.Game()
    const node = game.addVariation(new chess.Move(chess.E2, chess.E4))
    const alternativeNode = game.addVariation(new chess.Move(chess.D2, chess.D4))
    const endNode = node.addVariation(new chess.Move(chess.E7, chess.E5))

    this.assertEqualUsing(game.root(), game, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(node.root(), game, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(alternativeNode.root(), game, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(endNode.root(), game, (__actual, __expected) => __actual === __expected)

    this.assertEqualUsing(game.end(), endNode, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(node.end(), endNode, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(endNode.end(), endNode, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(alternativeNode.end(), alternativeNode, (__actual, __expected) => __actual === __expected)

    this.assertTrue(game.isMainline())
    this.assertTrue(node.isMainline())
    this.assertTrue(endNode.isMainline())
    this.assertFalse(alternativeNode.isMainline())

    this.assertFalse(game.startsVariation())
    this.assertFalse(node.startsVariation())
    this.assertFalse(endNode.startsVariation())
    this.assertTrue(alternativeNode.startsVariation())

    this.assertFalse(game.isEnd())
    this.assertFalse(node.isEnd())
    this.assertTrue(alternativeNode.isEnd())
    this.assertTrue(endNode.isEnd())
  }

  testPromoteDemote(): void {
    const game = new pgnModule.Game()
    const a = game.addVariation(new chess.Move(chess.A2, chess.A3))
    const b = game.addVariation(new chess.Move(chess.B2, chess.B3))

    this.assertTrue(a.isMainVariation())
    this.assertFalse(b.isMainVariation())
    this.assertEqualUsing(game.getitem(0), a, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(game.getitem(1), b, (__actual, __expected) => __actual === __expected)

    game.promote(b)
    this.assertTrue(b.isMainVariation())
    this.assertFalse(a.isMainVariation())
    this.assertEqualUsing(game.getitem(0), b, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(game.getitem(1), a, (__actual, __expected) => __actual === __expected)

    game.demote(b)
    this.assertTrue(a.isMainVariation())

    const c = game.addMainVariation(new chess.Move(chess.C2, chess.C3))
    this.assertTrue(c.isMainVariation())
    this.assertFalse(a.isMainVariation())
    this.assertFalse(b.isMainVariation())
    this.assertEqualUsing(game.getitem(0), c, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(game.getitem(1), a, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(game.getitem(2), b, (__actual, __expected) => __actual === __expected)
  }

  testAddLine(): void {
    const game = new pgnModule.Game()
    game.addVariation(chess.Move.fromUci("e2e4"))

    const moves = [chess.Move.fromUci("g1f3"), chess.Move.fromUci("d7d5")]

    const tail = ((__guardedValue) => { if (!(__guardedValue instanceof pgnModule.ChildNode)) throw new Error("compiler invariant failed: GameNode.add_line() received a non-empty exact move sequence but did not return ChildNode"); return __guardedValue; })(game.addLine(moves, { startingComment: "start", comment: "end", nags: [17, 42] }))

    this.assertEqualUsing(((__guardedValue) => { if (!(__guardedValue instanceof pgnModule.ChildNode)) throw new Error("compiler invariant failed: GameNode.add_line() received a non-empty exact move sequence but did not return ChildNode"); return __guardedValue; })(tail.parent).move, chess.Move.fromUci("g1f3"), (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(((__guardedValue) => { if (!(__guardedValue instanceof pgnModule.ChildNode)) throw new Error("compiler invariant failed: GameNode.add_line() received a non-empty exact move sequence but did not return ChildNode"); return __guardedValue; })(tail.parent).startingComment, "start", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(((__guardedValue) => { if (!(__guardedValue instanceof pgnModule.ChildNode)) throw new Error("compiler invariant failed: GameNode.add_line() received a non-empty exact move sequence but did not return ChildNode"); return __guardedValue; })(tail.parent).comment, "", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(((__guardedValue) => { if (!(__guardedValue instanceof pgnModule.ChildNode)) throw new Error("compiler invariant failed: GameNode.add_line() received a non-empty exact move sequence but did not return ChildNode"); return __guardedValue; })(tail.parent).nags.size, 0, (__actual, __expected) => __actual === __expected)

    this.assertEqualUsing(tail.move, chess.Move.fromUci("d7d5"), (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(tail.comment, "end", (__actual, __expected) => __actual === __expected)
    this.assertContainsUsing(42, tail.nags, (__container, __member) => __container.has(__member))
  }

  testMainline(): void {
    const moves = Array.from(["d2d3", "g8f6", "e2e4"], __uciItem => chess.Move.fromUci(__uciItem))

    const game = new pgnModule.Game()
    ;((__guardedValue) => { if (!(__guardedValue instanceof pgnModule.ChildNode)) throw new Error("compiler invariant failed: GameNode.add_line() received a non-empty exact move sequence but did not return ChildNode"); return __guardedValue; })(game.addLine(moves))

    this.assertEqualUsing(Array.from(game.mainlineMoves()), moves, (__actual, __expected) => __actual.length === __expected.length && __actual.every((__value0, __index0) => __expected.slice(__index0, __index0 + 1).some(__expected0 => __value0.equals(__expected0))))
    this.assertTrue(game.mainlineMoves().bool())
    this.assertEqualUsing(Array.from(game.mainlineMoves().reversed()), Array.from(((__sequence) => { const __length = __sequence.length; return (function* () { for (let __index = __length - 1; __index >= 0; __index -= 1) { const __value = __sequence.at(__index); if (__value === undefined) return; yield __value; } })(); })(moves)), (__actual, __expected) => __actual.length === __expected.length && __actual.every((__value0, __index0) => __expected.slice(__index0, __index0 + 1).some(__expected0 => __value0.equals(__expected0))))
    this.assertEqualUsing(game.mainlineMoves().toString(), "1. d3 Nf6 2. e4", (__actual, __expected) => __actual === __expected)
  }

  testAnnotations(): void {
    const game = new pgnModule.Game()
    ;((__newValue, __receiver) => { __receiver.comment = __newValue; })("foo [%bar] baz", game)

    this.assertTrue(((__left, __right) => __left === null)(game.clock(), null))
    const clock = 12345
    game.setClock(clock)
    this.assertEqualUsing(game.comment, "foo [%bar] baz [%clk 3:25:45]", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(game.clock(), clock, (__actual, __expected) => __actual !== null && (__actual === __expected))

    this.assertTrue(((__left, __right) => __left === null)(game.eval(), null))
    game.setEval(new engineModule.PovScore(new engineModule.Cp(-(80)), chess.WHITE))
    this.assertEqualUsing(game.comment, "foo [%bar] baz [%clk 3:25:45] [%eval -0.80]", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(game.eval()).white().score(), -(80), (__actual, __expected) => __actual !== null && (__actual === __expected))
    this.assertEqualUsing(game.evalDepth(), null, (__actual, __expected) => __actual === null)
    game.setEval(new engineModule.PovScore(new engineModule.Mate(1), chess.WHITE), 5)
    this.assertEqualUsing(game.comment, "foo [%bar] baz [%clk 3:25:45] [%eval #1,5]", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(((__receiver) => { if (__receiver === null) throw new TypeError("cannot access an attribute of null"); return __receiver; })(game.eval()).white().mate(), 1, (__actual, __expected) => __actual !== null && (__actual === __expected))
    this.assertEqualUsing(game.evalDepth(), 5, (__actual, __expected) => __actual !== null && (__actual === __expected))

    this.assertEqualUsing(game.arrows(), [], (__actual, __expected) => __actual.length === 0 && __expected.length === 0)
    game.setArrows(([[chess.A1, chess.A1], new svgModule.Arrow(chess.A1, chess.H1, { color: "red" }), new svgModule.Arrow(chess.B1, chess.B8)] satisfies (svgModule.Arrow | [number, number])[]))
    this.assertEqualUsing(game.comment, "[%csl Ga1][%cal Ra1h1,Gb1b8] foo [%bar] baz [%clk 3:25:45] [%eval #1,5]", (__actual, __expected) => __actual === __expected)
    const arrows = game.arrows()
    this.assertEqualUsing(arrows.length, 3, (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(((__sequence, __index) => { const __indexedValue = __sequence.at(__index); if (__indexedValue === undefined) throw new RangeError("array index out of range"); return __indexedValue; })(arrows, 0).color, "green", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(((__sequence, __index) => { const __indexedValue = __sequence.at(__index); if (__indexedValue === undefined) throw new RangeError("array index out of range"); return __indexedValue; })(arrows, 1).color, "red", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(((__sequence, __index) => { const __indexedValue = __sequence.at(__index); if (__indexedValue === undefined) throw new RangeError("array index out of range"); return __indexedValue; })(arrows, 2).color, "green", (__actual, __expected) => __actual === __expected)

    this.assertTrue(((__left, __right) => __left === null)(game.emt(), null))
    const emt = 321
    game.setEmt(emt)
    this.assertEqualUsing(game.comment, "[%csl Ga1][%cal Ra1h1,Gb1b8] foo [%bar] baz [%clk 3:25:45] [%eval #1,5] [%emt 0:05:21]", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(game.emt(), emt, (__actual, __expected) => __actual !== null && (__actual === __expected))

    game.setEval(null)
    this.assertEqualUsing(game.comment, "[%csl Ga1][%cal Ra1h1,Gb1b8] foo [%bar] baz [%clk 3:25:45] [%emt 0:05:21]", (__actual, __expected) => __actual === __expected)

    game.setEmt(null)
    this.assertEqualUsing(game.comment, "[%csl Ga1][%cal Ra1h1,Gb1b8] foo [%bar] baz [%clk 3:25:45]", (__actual, __expected) => __actual === __expected)

    game.setClock(null)
    game.setArrows([])
    this.assertEqualUsing(game.comment, "foo [%bar] baz", (__actual, __expected) => __actual === __expected)
  }

  testFloatEmt(): void {
    const game = new pgnModule.Game()
    ;((__newValue, __receiver) => { __receiver.comment = __newValue; })("[%emt 0:00:01.234]", game)
    this.assertEqualUsing(game.emt(), 1.234, (__actual, __expected) => __actual !== null && (__actual === __expected))

    game.setEmt(6.54321)
    this.assertEqualUsing(game.comment, "[%emt 0:00:06.543]", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(game.emt(), 6.543, (__actual, __expected) => __actual !== null && (__actual === __expected))

    game.setEmt(-(70))
    this.assertEqualUsing(game.comment, "[%emt 0:00:00]", (__actual, __expected) => __actual === __expected) // Clamped
    this.assertEqualUsing(game.emt(), 0, (__actual, __expected) => __actual !== null && (__actual === __expected))
  }

  testFloatClk(): void {
    const game = new pgnModule.Game()
    ;((__newValue, __receiver) => { __receiver.comment = __newValue; })("[%clk 0:00:01.234]", game)
    this.assertEqualUsing(game.clock(), 1.234, (__actual, __expected) => __actual !== null && (__actual === __expected))

    game.setClock(6.54321)
    this.assertEqualUsing(game.comment, "[%clk 0:00:06.543]", (__actual, __expected) => __actual === __expected)
    this.assertEqualUsing(game.clock(), 6.543, (__actual, __expected) => __actual !== null && (__actual === __expected))

    game.setClock(-(70))
    this.assertEqualUsing(game.comment, "[%clk 0:00:00]", (__actual, __expected) => __actual === __expected) // Clamped
    this.assertEqualUsing(game.clock(), 0, (__actual, __expected) => __actual !== null && (__actual === __expected))
  }
}

registerTestCase('PgnTestCase', PgnTestCase, {
  lines: {
    testExporter: 2089,
    testPromoteToMain: 2190,
    testCommentAtEol: 2228,
    testGameStartingComment: 2327,
    testGameStartingVariation: 2337,
    testTreeTraversal: 2377,
    testPromoteDemote: 2408,
    testAddLine: 2689,
    testMainline: 2706,
    testAnnotations: 2831,
    testFloatEmt: 2882,
    testFloatClk: 2895,
  },
})

/** Generated directly from the frozen python-chess syntax tree. */
class EngineTestCase extends TestCase {
  testScoreOrdering(): void {
    const order = [new engineModule.Mate(-(0)), new engineModule.Mate(-(1)), new engineModule.Mate(-(99)), new engineModule.Cp(-(123)), new engineModule.Cp(-(50)), new engineModule.Cp(0), new engineModule.Cp(+(30)), new engineModule.Cp(+(800)), new engineModule.Mate(+(77)), new engineModule.Mate(+(1)), engineModule.MateGiven]

    for (let [i, a] of ((__iterable) => (function* () { let __index = 0; for (const __value of __iterable) { yield [__index, __value] satisfies [number, typeof __value]; __index += 1; } })())(order)) {
      for (let [j, b] of ((__iterable) => (function* () { let __index = 0; for (const __value of __iterable) { yield [__index, __value] satisfies [number, typeof __value]; __index += 1; } })())(order)) {
        this.assertEqualUsing(((__left, __right) => __left < __right)(i, j), ((__left, __right) => __left.lt(__right))(a, b), (__actual, __expected) => __actual === __expected, `${a.toRepr()} < ${b.toRepr()}`)
        this.assertEqualUsing(((__left, __right) => __left === __right)(i, j), ((__left, __right) => __left.equals(__right))(a, b), (__actual, __expected) => __actual === __expected, `${a.toRepr()} == ${b.toRepr()}`)
        this.assertEqualUsing(((__left, __right) => __left <= __right)(i, j), ((__left, __right) => __left.le(__right))(a, b), (__actual, __expected) => __actual === __expected)
        this.assertEqualUsing(!(((__left, __right) => __left === __right)(i, j)), !(((__left, __right) => __left.equals(__right))(a, b)), (__actual, __expected) => __actual === __expected)
        this.assertEqualUsing(((__left, __right) => __left > __right)(i, j), ((__left, __right) => __left.gt(__right))(a, b), (__actual, __expected) => __actual === __expected)
        this.assertEqualUsing(((__left, __right) => __left >= __right)(i, j), ((__left, __right) => __left.ge(__right))(a, b), (__actual, __expected) => __actual === __expected)
        this.assertEqualUsing(((__left, __right) => __left < __right)(i, j), ((__left, __right) => (() => { if (__left === null || __right === null) throw new TypeError("cannot order null and a value"); return __left < __right; })())(a.score({ mateScore: 100000 }), b.score({ mateScore: 100000 })), (__actual, __expected) => __actual === __expected)

        for (let model of ["sf12", "sf14", "sf15", "sf15.1", "sf16", "sf16.1"]) {
          this.assertTrue((!(((__left, __right) => __left < __right)(i, j)) || ((__left, __right) => __left <= __right)(a.wdl({ model: ((__finiteString) => { switch (__finiteString) { case "sf12": case "sf14": case "sf15": case "sf15.1": case "sf16": case "sf16.1": return __finiteString; default: throw new Error("compiler invariant failed: finite string value " + JSON.stringify(__finiteString) + " escaped its proved set"); } })(model) }).expectation(), b.wdl({ model: ((__finiteString) => { switch (__finiteString) { case "sf12": case "sf14": case "sf15": case "sf15.1": case "sf16": case "sf16.1": return __finiteString; default: throw new Error("compiler invariant failed: finite string value " + JSON.stringify(__finiteString) + " escaped its proved set"); } })(model) }).expectation())))
          this.assertTrue((!(((__left, __right) => __left < __right)(i, j)) || ((__left, __right) => __left <= __right)(a.wdl({ model: ((__finiteString) => { switch (__finiteString) { case "sf12": case "sf14": case "sf15": case "sf15.1": case "sf16": case "sf16.1": return __finiteString; default: throw new Error("compiler invariant failed: finite string value " + JSON.stringify(__finiteString) + " escaped its proved set"); } })(model) }).winningChance(), b.wdl({ model: ((__finiteString) => { switch (__finiteString) { case "sf12": case "sf14": case "sf15": case "sf15.1": case "sf16": case "sf16.1": return __finiteString; default: throw new Error("compiler invariant failed: finite string value " + JSON.stringify(__finiteString) + " escaped its proved set"); } })(model) }).winningChance())))
          this.assertTrue((!(((__left, __right) => __left < __right)(i, j)) || ((__left, __right) => __left >= __right)(a.wdl({ model: ((__finiteString) => { switch (__finiteString) { case "sf12": case "sf14": case "sf15": case "sf15.1": case "sf16": case "sf16.1": return __finiteString; default: throw new Error("compiler invariant failed: finite string value " + JSON.stringify(__finiteString) + " escaped its proved set"); } })(model) }).losingChance(), b.wdl({ model: ((__finiteString) => { switch (__finiteString) { case "sf12": case "sf14": case "sf15": case "sf15.1": case "sf16": case "sf16.1": return __finiteString; default: throw new Error("compiler invariant failed: finite string value " + JSON.stringify(__finiteString) + " escaped its proved set"); } })(model) }).losingChance())))
        }
      }
    }
  }

  testWdlModel(): void {
    this.assertEqualUsing(new engineModule.Cp(131).wdl({ model: "sf12", ply: 25 }), new engineModule.Wdl(524, 467, 9), (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(new engineModule.Cp(146).wdl({ model: "sf14", ply: 25 }), new engineModule.Wdl(601, 398, 1), (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(new engineModule.Cp(40).wdl({ model: "sf15", ply: 25 }), new engineModule.Wdl(58, 937, 5), (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(new engineModule.Cp(100).wdl({ model: "sf15.1", ply: 64 }), new engineModule.Wdl(497, 503, 0), (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(new engineModule.Cp(-(52)).wdl({ model: "sf16", ply: 63 }), new engineModule.Wdl(0, 932, 68), (__actual, __expected) => __actual.equals(__expected))
    this.assertEqualUsing(new engineModule.Cp(51).wdl({ model: "sf16.1", ply: 158 }), new engineModule.Wdl(36, 964, 0), (__actual, __expected) => __actual.equals(__expected))
  }
}

registerTestCase('EngineTestCase', EngineTestCase, {
  lines: {
    testScoreOrdering: 2983,
    testWdlModel: 3042,
  },
})
